# test=error block 'a' already exists

4 main()
{
a:
	ret.4 5
a:
	ret.4 3
}
